export enum ReasonEnum {
  ROUTINE_EXAMS = 'EXAMENS DE ROUTINE',
  COMMONHE_ALTHISSUES = 'PROBLEMES DE SANTE COURANTS',
  SKIN_PROBLEMS = 'PROBLEMES DE PEAU',
  MENTAL_HEALTH = 'SANTE MENTALE',
  CHRONIC_CONDITIONS = 'AFFECTIONS CHRONIQUES',
  INJURIES = 'BLESSURES',
  SPECIALIZED_CONSULTATIONS = 'CONSULTATIONS SPECIALISEES',
  PREGNANCY = 'GROSSESSE',
  DENTAL_HEALTH = 'SANTE DENTAIRE',
  GERIATRIC_CARE = 'SOINS GERIATRIQUES',
}

export enum AnalysisTypeEnum {
  BLOOD_TEST = 'ANALYSE DE SANG',
  URINE_ANALYSIS = "ANALYSE D'URINE",
  X_RAY = 'RADIOGRAPHIE',
  MRI_SCAN = 'IRM',
  CT_SCAN = 'SCANNER',
  ULTRASOUND = 'ECHOGRAPHIE',
  BIOPSY = 'BIOPSIE',
  ECG = 'ECG',
  COLONOSCOPY = 'COLOSCOPIE',
  ENDOSCOPY = 'ENDOSCOPIE',
}

export enum PrescriptionTypeEnum {
  TO_BYE = 'A ACHETER',
  TO_INJECT = 'A INJECTER',
}

export enum AnalysisResultEnum {
  NORMAL = 'NORMAL',
  ABNORMAL = 'ANORMAL',
  ELEVATED = 'ELEVE',
  POSITIVE = 'POSITIF',
  NEGATIVE = 'NAGATIVE',
  INCONCLUSIVE = 'INCONCLUANT',
  ABSENT = 'ABSENT',
  PRESENT = 'PRESENT',
  OTHER = 'AUTRE',
}

export enum MedicationName {
  ASPIRIN = 'ASPIRINE',
  IBUPROFEN = 'IBUPROFÈNE',
  PARACETAMOL = 'PARACÉTAMOL',
  AMOXICILLIN = 'AMOXICILLINE',
  LIPITOR = 'LIPITOR',
  VITAMIN_C = 'VITAMINE C',
  ATENOLOL = 'ATÉNOLOL',
  LANSOPRAZOLE = 'LANSOPRAZOLE',
  ALBUTEROL = 'ALBUTÉROL',
  INSULIN = 'INSULINE',
  OTHER = 'AUTRE',
}

export enum HistoryTypeEnum {
  PATHOLOGICAL = 'PATHOLOGIQUE',
  SURGICAL = 'CHIRURGICAL',
  MEDICATION_ALLERGY = 'ALLERGIE MÉDICAMENTEUSE',
  GYNECO_OBSTETRIC = 'GYNÉCO-OBSTÉTRIQUE',
  FAMILY_HISTORY = 'ANTECÉDENTS FAMILIAUX',
  UROGENITAL = 'UROGÉNITAL',
  PARA_CLINICAL = 'PARA-CLINIQUE',
  SEXUAL_ACTIVITY = 'ACTIVITÉ SEXUELLE',
  HYGIENIC_DIETETIC = 'HYGIÉNO-DIÉTÉTIQUE',
  OTHER = 'AUTRE',
}


